import { type Deal } from "@/types/deal";

const now = new Date();
function daysAgo(d: number) {
  const dt = new Date(now);
  dt.setDate(dt.getDate() - d);
  return dt.toISOString();
}
function daysFromNow(d: number) {
  const dt = new Date(now);
  dt.setDate(dt.getDate() + d);
  return dt.toISOString();
}

export const MOCK_DEALS: Deal[] = [
  // ─── Lead ────────────────────────────────────────────────────────────────
  {
    id: "d1",
    athlete_name: "Gabriel Souza Martins",
    athlete_position: "Meio-campo",
    guardian_name: "Roberto Martins",
    guardian_profession: "Diretor Financeiro",
    investment_range: "30k-40k",
    deal_value_brl: 32000,
    stage: "lead",
    classification: "QUENTE",
    address_state: "SP",
    created_at: daysAgo(0),
    stage_updated_at: daysAgo(0),
    consultant: "Leandro Ribeiro",
    product_tier: "Legacy",
    next_action: "Enviar convite para reunião diagnóstica",
    next_action_date: daysFromNow(1),
  },
  {
    id: "d2",
    athlete_name: "Lucas Ferreira Lima",
    athlete_position: "Atacante",
    guardian_name: "Ana Ferreira",
    guardian_profession: "Analista de Marketing",
    investment_range: "18k-26k",
    deal_value_brl: 18000,
    stage: "lead",
    classification: "MORNO",
    address_state: "RJ",
    created_at: daysAgo(1),
    stage_updated_at: daysAgo(1),
    consultant: "Leandro Ribeiro",
    product_tier: "Start",
    next_action: "Follow-up de agendamento — lead não marcou reunião",
    next_action_date: daysFromNow(0),
  },

  // ─── Reunião Marcada ─────────────────────────────────────────────────────
  {
    id: "d15",
    athlete_name: "Arthur Lima Pereira",
    athlete_position: "Lateral Direito",
    guardian_name: "Marcos Pereira",
    guardian_profession: "Advogado",
    investment_range: "23k-32k",
    deal_value_brl: 26000,
    stage: "reuniao_marcada",
    classification: "QUENTE",
    address_state: "SP",
    created_at: daysAgo(2),
    stage_updated_at: daysAgo(1),
    consultant: "Leandro Ribeiro",
    product_tier: "Journey",
    next_action: "Realizar reunião diagnóstica",
    next_action_date: daysFromNow(2),
    notes: "Reunião marcada para quinta-feira às 19h via Google Meet.",
  },

  // ─── Reunião Realizada ───────────────────────────────────────────────────
  {
    id: "d3",
    athlete_name: "Caio Henrique Alves",
    athlete_position: "Goleiro",
    guardian_name: "Dr. Marcos Alves",
    guardian_profession: "Médico Cirurgião",
    investment_range: "28k-32k",
    deal_value_brl: 32000,
    stage: "reuniao_realizada",
    classification: "QUENTE",
    address_state: "MG",
    created_at: daysAgo(5),
    stage_updated_at: daysAgo(2),
    consultant: "Leandro Ribeiro",
    product_tier: "Legacy",
    next_action: "Confirmar fit e avançar para diagnóstico",
    next_action_date: daysFromNow(1),
    notes: "Pai muito interessado. Reunião durou 2h. Alta renda compatível.",
  },

  // ─── Diagnóstico / Fit Confirmado ─────────────────────────────────────────
  {
    id: "d16",
    athlete_name: "Bernardo Costa Silva",
    athlete_position: "Volante",
    guardian_name: "Luciana Silva",
    guardian_profession: "Empresária",
    investment_range: "23k-26k",
    deal_value_brl: 26000,
    stage: "diagnostico_fit",
    classification: "QUENTE",
    address_state: "PR",
    created_at: daysAgo(7),
    stage_updated_at: daysAgo(3),
    consultant: "Leandro Ribeiro",
    product_tier: "Journey",
    next_action: "Apresentar alinhamento estratégico personalizado",
    next_action_date: daysFromNow(2),
    notes: "Fit confirmado. Atleta com bom nível técnico e perfil acadêmico sólido.",
  },

  // ─── Alinhamento Estratégico ──────────────────────────────────────────────
  {
    id: "d17",
    athlete_name: "Davi Rodrigues Faria",
    athlete_position: "Meia Atacante",
    guardian_name: "Paulo Faria",
    guardian_profession: "Executivo de Banco",
    investment_range: "28k-32k",
    deal_value_brl: 32000,
    stage: "alinhamento_estrategico",
    classification: "QUENTE",
    address_state: "DF",
    created_at: daysAgo(10),
    stage_updated_at: daysAgo(4),
    consultant: "Leandro Ribeiro",
    product_tier: "Legacy",
    next_action: "Enviar proposta personalizada com escolas priorizadas",
    next_action_date: daysFromNow(1),
    notes: "Alinhamento apresentado. Família empolgada com as opções de escolas em FL.",
  },

  // ─── Proposta Enviada ───────────────────────────────────────────────────
  {
    id: "d4",
    athlete_name: "Felipe Castro Nunes",
    athlete_position: "Lateral Esquerdo",
    guardian_name: "Patricia Nunes",
    guardian_profession: "Empresária",
    investment_range: "23k-26k",
    deal_value_brl: 26000,
    stage: "proposta_enviada",
    classification: "QUENTE",
    address_state: "RS",
    created_at: daysAgo(8),
    stage_updated_at: daysAgo(3),
    consultant: "Leandro Ribeiro",
    product_tier: "Journey",
    next_action: "Follow-up da proposta — aguardar retorno",
    next_action_date: daysFromNow(2),
    notes: "Proposta PDF enviada. Aguardando retorno em 5 dias úteis.",
  },
  {
    id: "d5",
    athlete_name: "Eduardo Lima Rocha",
    athlete_position: "Meia",
    guardian_name: "Fernanda Rocha",
    guardian_profession: "CEO de Startup",
    investment_range: "28k-32k",
    deal_value_brl: 32000,
    stage: "proposta_enviada",
    classification: "QUENTE",
    address_state: "SP",
    created_at: daysAgo(12),
    stage_updated_at: daysAgo(5),
    consultant: "Leandro Ribeiro",
    product_tier: "Legacy",
    next_action: "Ligar para confirmar recebimento e tirar dúvidas",
    next_action_date: daysFromNow(0),
    notes: "Proposta personalizada Legacy enviada. Cliente muito analítico.",
  },

  // ─── Follow-up Proposta ──────────────────────────────────────────────────
  {
    id: "d18",
    athlete_name: "Enzo Martins Ribeiro",
    athlete_position: "Zagueiro",
    guardian_name: "Jorge Ribeiro",
    guardian_profession: "Médico Ortopedista",
    investment_range: "23k-26k",
    deal_value_brl: 26000,
    stage: "followup_proposta",
    classification: "QUENTE",
    address_state: "RJ",
    created_at: daysAgo(15),
    stage_updated_at: daysAgo(5),
    consultant: "Leandro Ribeiro",
    product_tier: "Journey",
    next_action: "Reunião para tirar dúvidas sobre a proposta",
    next_action_date: daysFromNow(1),
    notes: "Família com dúvidas sobre o processo acadêmico. Reunião marcada.",
  },

  // ─── Negociação ─────────────────────────────────────────────────────────
  {
    id: "d6",
    athlete_name: "Bruno Carvalho Neto",
    athlete_position: "Volante",
    guardian_name: "General Paulo Carvalho",
    guardian_profession: "Militar (General)",
    investment_range: "23k-26k",
    deal_value_brl: 26000,
    stage: "negociacao",
    classification: "QUENTE",
    address_state: "DF",
    created_at: daysAgo(18),
    stage_updated_at: daysAgo(6),
    consultant: "Leandro Ribeiro",
    product_tier: "Journey",
    has_discount: true,
    discount_pct: 8,
    next_action: "Aguardar decisão final sobre desconto",
    next_action_date: daysFromNow(1),
    notes: "Pedindo 10% de desconto. Oferecendo 8%. Decisão final amanhã.",
  },

  // ─── Contrato Enviado ────────────────────────────────────────────────────
  {
    id: "d19",
    athlete_name: "Henrique Almeida Braga",
    athlete_position: "Atacante Centro",
    guardian_name: "Fábio Braga",
    guardian_profession: "Pecuarista",
    investment_range: "28k-32k",
    deal_value_brl: 32000,
    stage: "contrato_enviado",
    classification: "QUENTE",
    address_state: "GO",
    created_at: daysAgo(20),
    stage_updated_at: daysAgo(2),
    consultant: "Leandro Ribeiro",
    product_tier: "Legacy",
    next_action: "Acompanhar assinatura do contrato via DocuSign",
    next_action_date: daysFromNow(1),
    notes: "Contrato enviado via DocuSign. Prazo de 48h para assinatura.",
  },

  // ─── Contrato Assinado ──────────────────────────────────────────────────
  {
    id: "d7",
    athlete_name: "Pedro Alves Costa",
    athlete_position: "Goleiro",
    guardian_name: "Carlos Costa",
    guardian_profession: "Engenheiro Civil",
    investment_range: "23k-26k",
    deal_value_brl: 26000,
    stage: "contrato_assinado",
    classification: "QUENTE",
    address_state: "MG",
    created_at: daysAgo(25),
    stage_updated_at: daysAgo(8),
    contract_signed_at: daysAgo(8),
    signal_value_brl: 4500,
    remaining_value_brl: 21500,
    consultant: "Leandro Ribeiro",
    product_tier: "Journey",
    next_action: "Confirmar recebimento do sinal de R$ 4.500",
    next_action_date: daysFromNow(0),
    notes: "Contrato assinado. Aguardando pagamento do sinal.",
  },
  {
    id: "d8",
    athlete_name: "Thiago Barbosa Almeida",
    athlete_position: "Atacante",
    guardian_name: "Silvio Almeida",
    guardian_profession: "Empresário do Agronegócio",
    investment_range: "28k-32k",
    deal_value_brl: 32000,
    stage: "contrato_assinado",
    classification: "QUENTE",
    address_state: "MT",
    created_at: daysAgo(22),
    stage_updated_at: daysAgo(5),
    contract_signed_at: daysAgo(5),
    signal_value_brl: 4500,
    remaining_value_brl: 27500,
    consultant: "Leandro Ribeiro",
    product_tier: "Legacy",
    next_action: "Sinal previsto para sexta — confirmar pagamento",
    next_action_date: daysFromNow(2),
    notes: "Contrato Legacy assinado. Sinal de R$ 4.500 previsto para sexta.",
  },

  // ─── Sinal Pago ────────────────────────────────────────────────────────
  {
    id: "d9",
    athlete_name: "Rafael Oliveira Mendes",
    athlete_position: "Zagueiro",
    guardian_name: "Fernando Mendes",
    guardian_profession: "Empresário",
    investment_range: "28k-32k",
    deal_value_brl: 32000,
    stage: "sinal_pago",
    classification: "QUENTE",
    address_state: "SC",
    created_at: daysAgo(35),
    stage_updated_at: daysAgo(12),
    contract_signed_at: daysAgo(18),
    signal_paid_at: daysAgo(12),
    signal_value_brl: 4500,
    remaining_value_brl: 27500,
    consultant: "Leandro Ribeiro",
    product_tier: "Legacy",
    next_action: "Iniciar processo de admission — enviar documentação para escolas",
    next_action_date: daysFromNow(1),
    notes: "Sinal confirmado. Início do processo de aplicação para outono 2026.",
  },

  // ─── Admission Process ──────────────────────────────────────────────────
  {
    id: "d10",
    athlete_name: "Victor Henrique Barbosa",
    athlete_position: "Ponta Esquerda",
    guardian_name: "Alexandre Barbosa",
    guardian_profession: "CEO",
    investment_range: "28k-32k",
    deal_value_brl: 32000,
    stage: "admission_process",
    classification: "QUENTE",
    address_state: "RS",
    created_at: daysAgo(50),
    stage_updated_at: daysAgo(15),
    contract_signed_at: daysAgo(40),
    signal_paid_at: daysAgo(30),
    signal_value_brl: 4500,
    remaining_value_brl: 27500,
    consultant: "Leandro Ribeiro",
    product_tier: "Legacy",
    next_action: "Acompanhar retorno de aceite da USF",
    next_action_date: daysFromNow(3),
    notes: "Aceite pela University of South Florida em análise! Aguardando resposta oficial.",
  },

  // ─── Concluído ─────────────────────────────────────────────────────────
  {
    id: "d12",
    athlete_name: "Guilherme Santos Prado",
    athlete_position: "Meio-campo",
    guardian_name: "Cristiane Prado",
    guardian_profession: "Advogada",
    investment_range: "23k-26k",
    deal_value_brl: 26000,
    stage: "concluido",
    classification: "QUENTE",
    address_state: "SP",
    created_at: daysAgo(120),
    stage_updated_at: daysAgo(20),
    contract_signed_at: daysAgo(100),
    signal_paid_at: daysAgo(90),
    signal_value_brl: 4500,
    remaining_value_brl: 21500,
    closed_at: daysAgo(20),
    consultant: "Leandro Ribeiro",
    product_tier: "Journey",
    notes: "Concluído! Atleta embarcou e está treinando na Keiser University.",
  },
  {
    id: "d11",
    athlete_name: "Mateus Oliveira Cruz",
    athlete_position: "Lateral Direito",
    guardian_name: "Roberto Cruz",
    guardian_profession: "Médico Pediatra",
    investment_range: "23k-26k",
    deal_value_brl: 26000,
    stage: "concluido",
    classification: "QUENTE",
    address_state: "PR",
    created_at: daysAgo(150),
    stage_updated_at: daysAgo(50),
    contract_signed_at: daysAgo(130),
    signal_paid_at: daysAgo(120),
    closed_at: daysAgo(50),
    signal_value_brl: 4500,
    remaining_value_brl: 21500,
    consultant: "Leandro Ribeiro",
    product_tier: "Journey",
    notes: "Concluído! Atleta na Florida Gulf Coast University.",
  },

  // ─── Perdido ───────────────────────────────────────────────────────────
  {
    id: "d13",
    athlete_name: "Thiago Andrade Souza",
    athlete_position: "Atacante",
    guardian_name: "Roberto Andrade",
    guardian_profession: "Técnico em Informática",
    investment_range: "16k-18k",
    deal_value_brl: 18000,
    stage: "perdido",
    classification: "FRIO",
    address_state: "BA",
    created_at: daysAgo(30),
    stage_updated_at: daysAgo(15),
    closed_at: daysAgo(15),
    consultant: "Leandro Ribeiro",
    product_tier: "Start",
    lost_reason: "Família sem capacidade financeira para o investimento atual.",
  },
  {
    id: "d14",
    athlete_name: "Henrique Rocha Lima",
    athlete_position: "Goleiro",
    guardian_name: "Sandra Lima",
    guardian_profession: "Professora",
    investment_range: "18k-23k",
    deal_value_brl: 18000,
    stage: "perdido",
    classification: "MORNO",
    address_state: "CE",
    created_at: daysAgo(45),
    stage_updated_at: daysAgo(25),
    closed_at: daysAgo(25),
    consultant: "Leandro Ribeiro",
    product_tier: "Start",
    lost_reason: "Decidiu por escola na Europa. Interesse futuro catalogado.",
    is_future_lead: true,
    future_project_year: 2027,
    future_reactivation_date: "2026-08-01",
  },
];

export function getDealsByStage(deals: Deal[]) {
  return deals.reduce<Record<string, Deal[]>>((acc, deal) => {
    if (!acc[deal.stage]) acc[deal.stage] = [];
    acc[deal.stage].push(deal);
    return acc;
  }, {});
}

const activeDeals = MOCK_DEALS.filter(
  (d) => d.stage !== "concluido" && d.stage !== "perdido"
);

const contractsAssinados = MOCK_DEALS.filter((d) => d.stage === "contrato_assinado");
const admissionProcess = MOCK_DEALS.filter((d) => d.stage === "admission_process");
const propostas = MOCK_DEALS.filter((d) => d.stage === "proposta_enviada" || d.stage === "followup_proposta");

export const MOCK_PIPELINE_METRICS = {
  total_pipeline_brl: activeDeals.reduce((s, d) => s + d.deal_value_brl, 0),
  active_deals: activeDeals.length,
  conversion_rate: 42,
  forecast_30d_brl: 120000,
  contracts_pending_signature: contractsAssinados.length,
  admission_in_progress: admissionProcess.length,
  proposals_pending: propostas.length,
  deals_without_next_action: activeDeals.filter((d) => !d.next_action).length,
};
