import { type Family } from "@/types/family";

const now = new Date();
function daysAgo(d: number) {
  const dt = new Date(now);
  dt.setDate(dt.getDate() - d);
  return dt.toISOString();
}
function daysFromNow(d: number) {
  const dt = new Date(now);
  dt.setDate(dt.getDate() + d);
  return dt.toISOString();
}

export const MOCK_FAMILIES_V2: Family[] = [
  // ─── Admissão ───────────────────────────────────────────────────────────
  {
    id: "fv1",
    athlete_name: "Pedro Alves Costa",
    athlete_position: "Goleiro",
    guardian_name: "Carlos Costa",
    email: "carlos.costa@email.com",
    whatsapp: "31991234567",
    plan: "Journey",
    journey_stage: "admissao",
    family_status: "satisfeita",
    temperature: "verde",
    anxiety_level: 2,
    satisfaction_level: 4,
    perceived_risk: 2,
    risk_profile: [
      { dimension: "academico", score: 2 },
      { dimension: "esportivo", score: 1 },
      { dimension: "emocional", score: 2 },
      { dimension: "financeiro", score: 3 },
      { dimension: "relacional", score: 1 },
      { dimension: "comunicacao", score: 2 },
    ],
    last_contact_at: daysAgo(3),
    last_contact_type: "whatsapp",
    next_contact_date: daysFromNow(4),
    days_without_contact: 3,
    contract_value_brl: 26000,
    contracted_at: daysAgo(30),
    target_school: "Florida Gulf Coast University",
    target_sport: "Futebol",
    address_state: "MG",
    attention_records: [],
    crisis_records: [],
    next_milestone: "Envio de transcrição oficial para escola",
    next_milestone_date: daysFromNow(10),
    consultant: "Leandro Ribeiro",
  },
  {
    id: "fv2",
    athlete_name: "Thiago Barbosa Almeida",
    athlete_position: "Atacante",
    guardian_name: "Silvio Almeida",
    email: "silvio.almeida@email.com",
    whatsapp: "65991234567",
    plan: "Legacy",
    journey_stage: "admissao",
    family_status: "atencao",
    temperature: "amarelo",
    anxiety_level: 4,
    satisfaction_level: 3,
    perceived_risk: 3,
    risk_profile: [
      { dimension: "academico", score: 3 },
      { dimension: "esportivo", score: 1 },
      { dimension: "emocional", score: 4 },
      { dimension: "financeiro", score: 2 },
      { dimension: "relacional", score: 2 },
      { dimension: "comunicacao", score: 3 },
    ],
    last_contact_at: daysAgo(6),
    last_contact_type: "ligacao",
    next_contact_date: daysFromNow(1),
    days_without_contact: 6,
    contract_value_brl: 32000,
    contracted_at: daysAgo(22),
    target_school: "University of South Florida",
    target_sport: "Futebol",
    address_state: "MT",
    attention_records: [
      {
        id: "ar1",
        problem_description: "Pai muito ansioso com prazo de resposta das escolas. Ligou 3x esta semana.",
        action_ongoing: "Chamada semanal de atualização estabelecida",
        next_action: "Ligar segunda-feira com atualização de status das aplicações",
        recorded_at: daysAgo(2),
      },
    ],
    crisis_records: [],
    next_milestone: "Primeira resposta de escola esperada",
    next_milestone_date: daysFromNow(15),
    consultant: "Leandro Ribeiro",
  },

  // ─── Aprovado ───────────────────────────────────────────────────────────
  {
    id: "fv3",
    athlete_name: "Rafael Oliveira Mendes",
    athlete_position: "Zagueiro",
    guardian_name: "Fernando Mendes",
    email: "fernando.mendes@email.com",
    whatsapp: "48991234567",
    plan: "Legacy",
    journey_stage: "aprovado",
    family_status: "satisfeita",
    temperature: "verde",
    anxiety_level: 2,
    satisfaction_level: 5,
    perceived_risk: 1,
    risk_profile: [
      { dimension: "academico", score: 1 },
      { dimension: "esportivo", score: 1 },
      { dimension: "emocional", score: 2 },
      { dimension: "financeiro", score: 2 },
      { dimension: "relacional", score: 1 },
      { dimension: "comunicacao", score: 1 },
    ],
    last_contact_at: daysAgo(2),
    last_contact_type: "reuniao",
    next_contact_date: daysFromNow(5),
    days_without_contact: 2,
    contract_value_brl: 32000,
    contracted_at: daysAgo(50),
    target_school: "Florida Gulf Coast University",
    target_sport: "Futebol",
    address_state: "SC",
    attention_records: [],
    crisis_records: [],
    next_milestone: "Assinatura do I-20 e abertura de processo de visto",
    next_milestone_date: daysFromNow(7),
    consultant: "Leandro Ribeiro",
  },

  // ─── Pré-embarque ────────────────────────────────────────────────────────
  {
    id: "fv4",
    athlete_name: "Victor Henrique Barbosa",
    athlete_position: "Ponta Esquerda",
    guardian_name: "Alexandre Barbosa",
    email: "alexandre.barbosa@email.com",
    whatsapp: "51991234567",
    plan: "Legacy",
    journey_stage: "pre_embarque",
    family_status: "atencao",
    temperature: "amarelo",
    anxiety_level: 4,
    satisfaction_level: 3,
    perceived_risk: 3,
    risk_profile: [
      { dimension: "academico", score: 2 },
      { dimension: "esportivo", score: 1 },
      { dimension: "emocional", score: 4 },
      { dimension: "financeiro", score: 2 },
      { dimension: "relacional", score: 3 },
      { dimension: "comunicacao", score: 2 },
    ],
    last_contact_at: daysAgo(4),
    last_contact_type: "whatsapp",
    next_contact_date: daysFromNow(3),
    days_without_contact: 4,
    contract_value_brl: 32000,
    contracted_at: daysAgo(75),
    expected_departure_date: daysFromNow(45),
    target_school: "University of South Florida",
    target_sport: "Futebol",
    address_state: "RS",
    attention_records: [
      {
        id: "ar2",
        problem_description: "Mãe com muita ansiedade sobre a adaptação do filho nos EUA. Medo da solidão.",
        action_ongoing: "Agendamento de sessão com psicóloga intercultural",
        next_action: "Sessão com psicóloga marcada para quinta-feira",
        recorded_at: daysAgo(1),
      },
    ],
    crisis_records: [],
    next_milestone: "Entrevista visto F-1 no consulado",
    next_milestone_date: daysFromNow(21),
    consultant: "Leandro Ribeiro",
  },

  // ─── Embarcado ──────────────────────────────────────────────────────────
  {
    id: "fv5",
    athlete_name: "Guilherme Santos Prado",
    athlete_position: "Meio-campo",
    guardian_name: "Cristiane Prado",
    email: "cristiane.prado@email.com",
    whatsapp: "11991234567",
    plan: "Journey",
    journey_stage: "embarcado",
    family_status: "satisfeita",
    temperature: "verde",
    anxiety_level: 3,
    satisfaction_level: 4,
    perceived_risk: 2,
    risk_profile: [
      { dimension: "academico", score: 3 },
      { dimension: "esportivo", score: 2 },
      { dimension: "emocional", score: 3 },
      { dimension: "financeiro", score: 2 },
      { dimension: "relacional", score: 2 },
      { dimension: "comunicacao", score: 2 },
    ],
    last_contact_at: daysAgo(5),
    last_contact_type: "whatsapp",
    next_contact_date: daysFromNow(2),
    days_without_contact: 5,
    contract_value_brl: 26000,
    contracted_at: daysAgo(100),
    embarked_at: daysAgo(20),
    expected_departure_date: daysAgo(20),
    target_school: "Keiser University",
    target_sport: "Futebol",
    address_state: "SP",
    attention_records: [],
    crisis_records: [],
    next_milestone: "Check-in de 30 dias pós-embarque",
    next_milestone_date: daysFromNow(10),
    consultant: "Leandro Ribeiro",
  },

  // ─── Crise ──────────────────────────────────────────────────────────────
  {
    id: "fv6",
    athlete_name: "Mateus Oliveira Cruz",
    athlete_position: "Lateral Direito",
    guardian_name: "Roberto Cruz",
    email: "roberto.cruz@email.com",
    whatsapp: "41991234567",
    plan: "Journey",
    journey_stage: "acompanhamento",
    family_status: "crise",
    temperature: "vermelho",
    anxiety_level: 5,
    satisfaction_level: 2,
    perceived_risk: 5,
    risk_profile: [
      { dimension: "academico", score: 4 },
      { dimension: "esportivo", score: 3 },
      { dimension: "emocional", score: 5 },
      { dimension: "financeiro", score: 4 },
      { dimension: "relacional", score: 4 },
      { dimension: "comunicacao", score: 3 },
    ],
    last_contact_at: daysAgo(1),
    last_contact_type: "ligacao",
    next_contact_date: daysFromNow(1),
    days_without_contact: 1,
    contract_value_brl: 26000,
    contracted_at: daysAgo(150),
    embarked_at: daysAgo(55),
    expected_departure_date: daysAgo(55),
    target_school: "Florida Gulf Coast University",
    target_sport: "Futebol",
    address_state: "PR",
    attention_records: [],
    crisis_records: [
      {
        id: "cr1",
        description: "Atleta com dificuldade severa de adaptação. Notas caindo, considerando retorno ao Brasil.",
        crisis_type: "Emocional + Acadêmico",
        crisis_level: 4,
        action_taken: "Ligação de emergência com família e atleta. Psicóloga intercultural acionada imediatamente.",
        psychologist_activated: true,
        recorded_at: daysAgo(2),
      },
    ],
    next_milestone: "Sessão de crise com psicóloga + reunião com coach",
    next_milestone_date: daysFromNow(2),
    consultant: "Leandro Ribeiro",
  },
];

export const MOCK_FAMILY_V2_METRICS = {
  total: MOCK_FAMILIES_V2.length,
  satisfeita: MOCK_FAMILIES_V2.filter((f) => f.family_status === "satisfeita").length,
  atencao: MOCK_FAMILIES_V2.filter((f) => f.family_status === "atencao").length,
  crise: MOCK_FAMILIES_V2.filter((f) => f.family_status === "crise").length,
  avg_satisfaction: +(MOCK_FAMILIES_V2.reduce((s, f) => s + f.satisfaction_level, 0) / MOCK_FAMILIES_V2.length).toFixed(1),
  avg_anxiety: +(MOCK_FAMILIES_V2.reduce((s, f) => s + f.anxiety_level, 0) / MOCK_FAMILIES_V2.length).toFixed(1),
  temperatura_verde: MOCK_FAMILIES_V2.filter((f) => f.temperature === "verde").length,
  temperatura_amarelo: MOCK_FAMILIES_V2.filter((f) => f.temperature === "amarelo").length,
  temperatura_vermelho: MOCK_FAMILIES_V2.filter((f) => f.temperature === "vermelho").length,
};
