import { type Family } from "@/types/family";

const now = new Date();
function daysAgo(d: number) {
  const dt = new Date(now);
  dt.setDate(dt.getDate() - d);
  return dt.toISOString();
}
function daysFromNow(d: number) {
  const dt = new Date(now);
  dt.setDate(dt.getDate() + d);
  return dt.toISOString();
}

// Dados legados — usados pela página /families (UI legada)
// Para o novo CRM use MOCK_FAMILIES_V2 em mock-families-v2.ts
const DEFAULT_RISK_PROFILE = [
  { dimension: "academico" as const, score: 2 },
  { dimension: "esportivo" as const, score: 1 },
  { dimension: "emocional" as const, score: 2 },
  { dimension: "financeiro" as const, score: 2 },
  { dimension: "relacional" as const, score: 1 },
  { dimension: "comunicacao" as const, score: 2 },
];

export const MOCK_FAMILIES: Family[] = [
  {
    id: "f1",
    athlete_name: "Victor Henrique Barbosa",
    athlete_position: "Ponta Esquerda",
    guardian_name: "Alexandre Barbosa",
    email: "victor.barbosa@gmail.com",
    whatsapp: "51910987653",
    plan: "Legacy",
    journey_stage: "admissao",
    family_status: "satisfeita",
    temperature: "verde",
    anxiety_level: 2,
    satisfaction_level: 5,
    perceived_risk: 1,
    risk_profile: DEFAULT_RISK_PROFILE,
    last_contact_at: daysAgo(2),
    last_contact_type: "whatsapp",
    next_contact_date: daysFromNow(5),
    days_without_contact: 2,
    contract_value_brl: 32000,
    contracted_at: daysAgo(45),
    target_school: "University of South Florida",
    target_university: "University of South Florida",
    target_sport: "Futebol",
    address_state: "RS",
    attention_records: [],
    crisis_records: [],
    next_milestone: "Prova de nivelamento de inglês",
    next_milestone_date: daysFromNow(8),
    alerts: [],
    nps_score: 10,
    risk_level: "baixo",
    emotional_temperature: "otimo",
    consultant_notes: "Família muito engajada. Atleta já iniciou curso de inglês intensivo.",
    consultant: "Leandro Ribeiro",
  },
  {
    id: "f2",
    athlete_name: "Rafael Oliveira Mendes",
    athlete_position: "Zagueiro",
    guardian_name: "Fernando Mendes",
    email: "rafael.mendes@email.com",
    whatsapp: "47943210986",
    plan: "Legacy",
    journey_stage: "aprovado",
    family_status: "satisfeita",
    temperature: "verde",
    anxiety_level: 2,
    satisfaction_level: 4,
    perceived_risk: 1,
    risk_profile: DEFAULT_RISK_PROFILE,
    last_contact_at: daysAgo(5),
    last_contact_type: "whatsapp",
    next_contact_date: daysFromNow(2),
    days_without_contact: 5,
    contract_value_brl: 32000,
    contracted_at: daysAgo(90),
    target_school: "Florida Gulf Coast University",
    target_university: "Florida Gulf Coast University",
    target_sport: "Futebol",
    address_state: "SC",
    attention_records: [],
    crisis_records: [],
    next_milestone: "Envio do vídeo de highlights atualizado",
    next_milestone_date: daysFromNow(3),
    alerts: [],
    nps_score: 9,
    risk_level: "baixo",
    emotional_temperature: "bem",
    consultant_notes: "Destaque no campeonato regional. Coaches americanos interessados.",
    consultant: "Leandro Ribeiro",
  },
  {
    id: "f3",
    athlete_name: "Bruno Carvalho Neto",
    athlete_position: "Volante",
    guardian_name: "General Paulo Carvalho",
    email: "bruno.neto@email.com",
    whatsapp: "61921098764",
    plan: "Journey",
    journey_stage: "admissao",
    family_status: "atencao",
    temperature: "amarelo",
    anxiety_level: 3,
    satisfaction_level: 3,
    perceived_risk: 3,
    risk_profile: DEFAULT_RISK_PROFILE,
    last_contact_at: daysAgo(8),
    last_contact_type: "whatsapp",
    next_contact_date: daysFromNow(1),
    days_without_contact: 8,
    contract_value_brl: 26000,
    contracted_at: daysAgo(15),
    target_school: "University of Central Florida",
    target_university: "University of Central Florida",
    target_sport: "Futebol",
    address_state: "DF",
    attention_records: [],
    crisis_records: [],
    next_milestone: "Reunião de onboarding completo",
    next_milestone_date: daysFromNow(2),
    alerts: ["Sem contato há 8 dias — agendar check-in"],
    nps_score: 7,
    risk_level: "medio",
    emotional_temperature: "atento",
    consultant_notes: "Pai (militar) bem criterioso. Precisa de atenção extra no início.",
    consultant: "Leandro Ribeiro",
  },
  {
    id: "f4",
    athlete_name: "Lucas Felipe Andrade",
    athlete_position: "Atacante",
    guardian_name: "Marcela Andrade",
    email: "lucas.andrade@gmail.com",
    whatsapp: "11934567890",
    plan: "Legacy",
    journey_stage: "pre_embarque",
    family_status: "satisfeita",
    temperature: "verde",
    anxiety_level: 2,
    satisfaction_level: 5,
    perceived_risk: 1,
    risk_profile: DEFAULT_RISK_PROFILE,
    last_contact_at: daysAgo(1),
    last_contact_type: "reuniao",
    next_contact_date: daysFromNow(3),
    days_without_contact: 1,
    contract_value_brl: 32000,
    contracted_at: daysAgo(120),
    target_school: "Florida State University",
    target_university: "Florida State University",
    target_sport: "Futebol",
    address_state: "SP",
    attention_records: [],
    crisis_records: [],
    next_milestone: "Início do processo de visto F-1",
    next_milestone_date: daysFromNow(5),
    alerts: [],
    nps_score: 10,
    risk_level: "baixo",
    emotional_temperature: "otimo",
    consultant_notes: "Aceite confirmado! Família emocionada. Processo de visto iniciando.",
    consultant: "Leandro Ribeiro",
  },
  {
    id: "f5",
    athlete_name: "Gustavo Ferreira Lopes",
    athlete_position: "Meia-atacante",
    guardian_name: "Carlos Lopes",
    email: "gustavo.lopes@email.com",
    whatsapp: "21987654321",
    plan: "Journey",
    journey_stage: "pre_embarque",
    family_status: "crise",
    temperature: "vermelho",
    anxiety_level: 5,
    satisfaction_level: 2,
    perceived_risk: 5,
    risk_profile: DEFAULT_RISK_PROFILE,
    last_contact_at: daysAgo(12),
    last_contact_type: "ligacao",
    next_contact_date: daysFromNow(0),
    days_without_contact: 12,
    contract_value_brl: 26000,
    contracted_at: daysAgo(150),
    target_school: "University of Texas at San Antonio",
    target_university: "University of Texas at San Antonio",
    target_sport: "Futebol",
    address_state: "RJ",
    attention_records: [],
    crisis_records: [],
    next_milestone: "Entrevista consular agendada",
    next_milestone_date: daysFromNow(1),
    alerts: [
      "Visto negado uma vez — nova tentativa amanhã",
      "Família ansiosa — ligar hoje",
      "Prazo de matrícula em 30 dias",
    ],
    nps_score: 5,
    risk_level: "alto",
    emotional_temperature: "preocupante",
    consultant_notes: "Primeira tentativa de visto negada por documentação incompleta. Corrigida. Família em estado de estresse elevado.",
    consultant: "Leandro Ribeiro",
  },
  {
    id: "f6",
    athlete_name: "Matheus Ribeiro Costa",
    athlete_position: "Lateral Direito",
    guardian_name: "Sandra Costa",
    email: "matheus.costa@email.com",
    whatsapp: "31965432108",
    plan: "Journey",
    journey_stage: "embarcado",
    family_status: "atencao",
    temperature: "amarelo",
    anxiety_level: 3,
    satisfaction_level: 4,
    perceived_risk: 2,
    risk_profile: DEFAULT_RISK_PROFILE,
    last_contact_at: daysAgo(6),
    last_contact_type: "whatsapp",
    next_contact_date: daysFromNow(1),
    days_without_contact: 6,
    contract_value_brl: 26000,
    contracted_at: daysAgo(180),
    target_school: "University of South Carolina",
    target_university: "University of South Carolina",
    target_sport: "Futebol",
    address_state: "MG",
    attention_records: [],
    crisis_records: [],
    next_milestone: "Primeiro treino oficial com o time",
    next_milestone_date: daysFromNow(4),
    alerts: ["Dificuldade de adaptação cultural — monitorar"],
    nps_score: 8,
    risk_level: "medio",
    emotional_temperature: "bem",
    consultant_notes: "Atleta chegou há 2 semanas. Adaptação normal mas com saudade de casa. Importante manter contato semanal.",
    consultant: "Leandro Ribeiro",
  },
];

export const MOCK_FAMILY_METRICS = {
  total_active: MOCK_FAMILIES.length,
  at_risk: MOCK_FAMILIES.filter((f) => f.risk_level === "alto" || f.risk_level === "critico").length,
  nps_average: Math.round(
    MOCK_FAMILIES.filter((f) => f.nps_score !== null && f.nps_score !== undefined).reduce((s, f) => s + (f.nps_score ?? 0), 0) /
    MOCK_FAMILIES.filter((f) => f.nps_score !== null && f.nps_score !== undefined).length
  ),
  milestones_this_week: MOCK_FAMILIES.filter((f) => {
    const milestone = new Date(f.next_milestone_date);
    const weekFromNow = new Date();
    weekFromNow.setDate(weekFromNow.getDate() + 7);
    return milestone <= weekFromNow;
  }).length,
};
