import { type School, type SchoolStageStrategy } from "@/types/school";

export const MOCK_SCHOOLS: School[] = [
  {
    id: "s1",
    name: "University of South Florida",
    state: "FL",
    city: "Tampa",
    type: "Division I",
    status: "ativa",
    min_budget_usd: 25000,
    strong_budget_usd: 40000,
    sport_influence: "alta",
    elite_athlete_exception: true,
    scholarship_aggressiveness: "agressiva",
    min_english_level: "Intermediário",
    required_tests: ["Duolingo"],
    preferred_grade: "10th",
    max_grade_accepted: "11th",
    total_applications: 12,
    acceptance_count: 9,
    avg_scholarship_pct: 68,
    avg_response_days: 21,
    practical_rule: "35k+ praticamente entra. Abaixo de 30k só atleta elite.",
    coach_name: "Coach Michael Davis",
    coach_email: "m.davis@usf.edu",
    notes: "Parceria sólida. Coach muito receptivo a atletas brasileiros.",
  },
  {
    id: "s2",
    name: "Florida Gulf Coast University",
    state: "FL",
    city: "Fort Myers",
    type: "Division I",
    status: "ativa",
    min_budget_usd: 22000,
    strong_budget_usd: 35000,
    sport_influence: "decisiva",
    elite_athlete_exception: true,
    scholarship_aggressiveness: "agressiva",
    min_english_level: "Básico-Intermediário",
    required_tests: ["Duolingo"],
    preferred_grade: "9th",
    max_grade_accepted: "11th",
    total_applications: 8,
    acceptance_count: 7,
    avg_scholarship_pct: 75,
    avg_response_days: 14,
    practical_rule: "Alta receptividade a atletas de qualidade. Budget secundário.",
    coach_name: "Coach Sarah Johnson",
    coach_email: "s.johnson@fgcu.edu",
    notes: "Melhor taxa de aceite da nossa rede. Coach extremamente parceira.",
  },
  {
    id: "s3",
    name: "Stetson University",
    state: "FL",
    city: "DeLand",
    type: "Division I",
    status: "ativa",
    min_budget_usd: 30000,
    strong_budget_usd: 45000,
    sport_influence: "media",
    elite_athlete_exception: false,
    scholarship_aggressiveness: "moderada",
    min_english_level: "Intermediário",
    required_tests: ["Duolingo", "SSAT"],
    preferred_grade: "10th",
    max_grade_accepted: "11th",
    total_applications: 5,
    acceptance_count: 3,
    avg_scholarship_pct: 55,
    avg_response_days: 28,
    practical_rule: "Exige budget sólido + nível acadêmico acima da média.",
    coach_name: "Coach Robert Wilson",
    notes: "Processo seletivo mais rigoroso. Escola de prestígio acadêmico.",
  },
  {
    id: "s4",
    name: "Embry-Riddle Aeronautical University",
    state: "FL",
    city: "Daytona Beach",
    type: "Division II",
    status: "ativa",
    min_budget_usd: 20000,
    strong_budget_usd: 32000,
    sport_influence: "alta",
    elite_athlete_exception: false,
    scholarship_aggressiveness: "moderada",
    min_english_level: "Básico",
    required_tests: ["Duolingo"],
    preferred_grade: "9th",
    max_grade_accepted: "12th",
    total_applications: 4,
    acceptance_count: 4,
    avg_scholarship_pct: 60,
    avg_response_days: 18,
    practical_rule: "Aceita perfis mais jovens. Boa bolsa esportiva.",
    notes: "Excelente para atletas com perfil técnico/engenharia.",
  },
  {
    id: "s5",
    name: "Lynn University",
    state: "FL",
    city: "Boca Raton",
    type: "Division II",
    status: "ativa",
    min_budget_usd: 28000,
    strong_budget_usd: 42000,
    sport_influence: "alta",
    elite_athlete_exception: false,
    scholarship_aggressiveness: "agressiva",
    min_english_level: "Intermediário",
    required_tests: ["Duolingo"],
    preferred_grade: "10th",
    max_grade_accepted: "11th",
    total_applications: 6,
    acceptance_count: 5,
    avg_scholarship_pct: 65,
    avg_response_days: 16,
    practical_rule: "Localização premium em Boca Raton. Budget médio-alto.",
    coach_name: "Coach Amanda Torres",
    coach_email: "a.torres@lynn.edu",
    notes: "Ambiente multicultural. Muitos alunos internacionais.",
  },
  {
    id: "s6",
    name: "Nova Southeastern University",
    state: "FL",
    city: "Fort Lauderdale",
    type: "Division II",
    status: "ativa",
    min_budget_usd: 18000,
    strong_budget_usd: 30000,
    sport_influence: "alta",
    elite_athlete_exception: true,
    scholarship_aggressiveness: "agressiva",
    min_english_level: "Básico",
    required_tests: ["Duolingo"],
    preferred_grade: "9th",
    max_grade_accepted: "12th",
    total_applications: 7,
    acceptance_count: 6,
    avg_scholarship_pct: 70,
    avg_response_days: 12,
    practical_rule: "Perfil muito receptivo. Aceita atletas com budget menor se nível esportivo for alto.",
    coach_name: "Coach James Miller",
    notes: "Grande volume de brasileiros. Comunidade de apoio estabelecida.",
  },
  {
    id: "s7",
    name: "Rollins College",
    state: "FL",
    city: "Winter Park",
    type: "Division III",
    status: "ativa",
    min_budget_usd: 35000,
    strong_budget_usd: 55000,
    sport_influence: "baixa",
    elite_athlete_exception: false,
    scholarship_aggressiveness: "conservadora",
    min_english_level: "Avançado",
    required_tests: ["Duolingo", "PSAT", "SSAT"],
    preferred_grade: "10th",
    max_grade_accepted: "10th",
    total_applications: 3,
    acceptance_count: 1,
    avg_scholarship_pct: 20,
    avg_response_days: 45,
    practical_rule: "Perfil acadêmico exigente. Bolsa esportiva quase inexistente.",
    notes: "Só recomendado para atletas com excelência acadêmica e budget alto.",
  },
  {
    id: "s8",
    name: "Keiser University",
    state: "FL",
    city: "West Palm Beach",
    type: "NAIA",
    status: "ativa",
    min_budget_usd: 15000,
    strong_budget_usd: 25000,
    sport_influence: "decisiva",
    elite_athlete_exception: true,
    scholarship_aggressiveness: "agressiva",
    min_english_level: "Básico",
    required_tests: ["Duolingo"],
    preferred_grade: "9th",
    max_grade_accepted: "12th",
    total_applications: 9,
    acceptance_count: 9,
    avg_scholarship_pct: 80,
    avg_response_days: 10,
    practical_rule: "Budget mais acessível. Bolsa muito agressiva para atletas de qualidade.",
    coach_name: "Coach Carlos Rodrigues",
    coach_email: "c.rodrigues@keiseruniversity.edu",
    notes: "Coach brasileiro facilita muito a adaptação. Excelente custo-benefício.",
  },
  {
    id: "s9",
    name: "Trinity Christian College",
    state: "IL",
    city: "Palos Heights",
    type: "NAIA",
    status: "ativa",
    min_budget_usd: 12000,
    strong_budget_usd: 20000,
    sport_influence: "decisiva",
    elite_athlete_exception: false,
    scholarship_aggressiveness: "agressiva",
    min_english_level: "Básico",
    required_tests: ["Duolingo"],
    preferred_grade: "9th",
    max_grade_accepted: "12th",
    total_applications: 4,
    acceptance_count: 4,
    avg_scholarship_pct: 85,
    avg_response_days: 8,
    practical_rule: "Budget mais baixo aceito. Atleta de qualidade é suficiente.",
    notes: "Inverno rigoroso. Boa opção para famílias com budget mais restrito.",
  },
  {
    id: "s10",
    name: "Indian River State College",
    state: "FL",
    city: "Fort Pierce",
    type: "JUCO",
    status: "ativa",
    min_budget_usd: 8000,
    strong_budget_usd: 15000,
    sport_influence: "decisiva",
    elite_athlete_exception: false,
    scholarship_aggressiveness: "agressiva",
    min_english_level: "Básico",
    required_tests: ["Duolingo"],
    preferred_grade: "9th",
    max_grade_accepted: "12th",
    total_applications: 5,
    acceptance_count: 5,
    avg_scholarship_pct: 90,
    avg_response_days: 7,
    practical_rule: "JUCO como trampolim para D1/D2. Budget muito acessível.",
    coach_name: "Coach Tony Hernandez",
    notes: "Estratégia de 2 anos para atletas com inglês limitado ou budget restrito.",
  },
  {
    id: "s11",
    name: "University of Central Florida",
    state: "FL",
    city: "Orlando",
    type: "Division I",
    status: "em_avaliacao",
    min_budget_usd: 40000,
    strong_budget_usd: 60000,
    sport_influence: "media",
    elite_athlete_exception: true,
    scholarship_aggressiveness: "conservadora",
    min_english_level: "Avançado",
    required_tests: ["Duolingo", "SAT"],
    preferred_grade: "10th",
    max_grade_accepted: "11th",
    total_applications: 2,
    acceptance_count: 0,
    avg_scholarship_pct: 0,
    avg_response_days: 60,
    practical_rule: "Processo em avaliação. Muito exigente academicamente.",
    notes: "Contato inicial estabelecido. Ainda sem aceite de atleta BAUSA.",
  },
  {
    id: "s12",
    name: "Webber International University",
    state: "FL",
    city: "Babson Park",
    type: "NAIA",
    status: "ativa",
    min_budget_usd: 14000,
    strong_budget_usd: 22000,
    sport_influence: "alta",
    elite_athlete_exception: false,
    scholarship_aggressiveness: "agressiva",
    min_english_level: "Básico",
    required_tests: ["Duolingo"],
    preferred_grade: "9th",
    max_grade_accepted: "12th",
    total_applications: 3,
    acceptance_count: 3,
    avg_scholarship_pct: 78,
    avg_response_days: 11,
    practical_rule: "Pequena mas receptiva. Budget acessível com boa bolsa.",
    notes: "Campus pequeno e bem estruturado. Ambiente familiar.",
  },
];

export const MOCK_SCHOOL_STRATEGIES: SchoolStageStrategy[] = [
  {
    id: "ss1",
    deal_id: "d9",
    athlete_name: "Rafael Oliveira Mendes",
    school_id: "s1",
    school_name: "University of South Florida",
    priority: 1,
    status: "pre_acordada",
    estimated_scholarship_usd: 15000,
    notes: "Coach confirmou interesse. Vídeo avaliado positivamente.",
  },
  {
    id: "ss2",
    deal_id: "d9",
    athlete_name: "Rafael Oliveira Mendes",
    school_id: "s2",
    school_name: "Florida Gulf Coast University",
    priority: 2,
    status: "rede_ativa",
    estimated_scholarship_usd: 20000,
    notes: "Coach em contato ativo. Aguardando transcrição oficial.",
  },
  {
    id: "ss3",
    deal_id: "d9",
    athlete_name: "Rafael Oliveira Mendes",
    school_id: "s5",
    school_name: "Lynn University",
    priority: 3,
    status: "planejamento",
    estimated_scholarship_usd: 12000,
  },
];
