import { type Lead, type LeadMetrics, type DailyLeadCount } from "@/types/lead";

const now = new Date();

function daysAgo(days: number): string {
  const d = new Date(now);
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

export const MOCK_LEADS: Lead[] = [
  {
    id: "1",
    submission_id: "sub_001",
    submitted_at: daysAgo(0),
    updated_at: daysAgo(0),
    athlete_name: "Gabriel Souza Martins",
    email: "gabriel.martins@email.com",
    birth_date: "2008-03-15",
    age: "17",
    athlete_whatsapp: "11987654321",
    position: "Meio-campo",
    club_history: "Flamengo Sub-17 (2 anos), CR Vasco Sub-15",
    achievements: "Campeão Paulistão Sub-17 2023, Convocado para Seleção Brasileira Sub-16",
    video_highlights: "https://youtube.com/watch?v=abc123",
    instagram: "@gabriel_martins10",
    school_year: "3º ano EM",
    current_school: "Colégio Elite São Paulo",
    school_city_state: "São Paulo - SP",
    education_model: "Particular",
    english_level: "Intermediário",
    academic_performance: "Bom (7-8)",
    start_timing: "2025",
    project_direction: "High School + Universidade",
    investment_range: "40k-50k",
    behavioral_profile: "Comprometido e disciplinado",
    youth_commitment: "Sim, treina todos os dias",
    family_decision_structure: "Pai e mãe decidem juntos",
    guardian_name: "Roberto Martins",
    guardian_email: "roberto.martins@empresa.com",
    guardian_whatsapp: "11987654320",
    guardian_profession: "Diretor Financeiro",
    address_cep: "01310-100",
    address_street: "Av. Paulista",
    address_number: "1578",
    address_complement: "Apto 42",
    address_neighborhood: "Bela Vista",
    address_city: "São Paulo",
    address_state: "SP",
    status: "new",
    notes: null,
    qualified: true,
    qualification_classification: "QUENTE",
    qualification_reason: "Diretor Financeiro — renda compatível com faixa de US$ 40-50k. Atleta com trajetória sólida em clube de expressão nacional.",
    qualification_confidence: "ALTA",
    qualified_at: daysAgo(0),
    whatsapp_sent_at: null,
    followup_1_sent_at: null,
    followup_2_sent_at: null,
    meeting_scheduled: null,
    meeting_scheduled_at: null,
    address_country: "BR",
    utm_source: null, utm_medium: null, utm_campaign: null, utm_content: null, utm_term: null, referrer_url: null, landing_url: null, session_id: null, cta_source: null, device_type: null, form_started_at: null,
    is_in_pipeline: true,
    pipeline_stage: "reuniao_marcada",
    pipeline_deal_id: "deal_001",
    pipeline_atleta_id: "atleta_001",
  },
  {
    id: "2",
    submission_id: "sub_002",
    submitted_at: daysAgo(1),
    updated_at: daysAgo(1),
    athlete_name: "Lucas Ferreira Lima",
    email: "lucas.lima@gmail.com",
    birth_date: "2007-11-22",
    age: "17",
    athlete_whatsapp: "21976543210",
    position: "Atacante",
    club_history: "Botafogo Sub-17",
    achievements: "Artilheiro do Campeonato Carioca Sub-17",
    video_highlights: "https://youtube.com/watch?v=def456",
    instagram: "@lucaslima9",
    school_year: "2º ano EM",
    current_school: "Colégio Pedro II",
    school_city_state: "Rio de Janeiro - RJ",
    education_model: "Público",
    english_level: "Básico",
    academic_performance: "Regular (5-6)",
    start_timing: "2026",
    project_direction: "High School",
    investment_range: "20k-30k",
    behavioral_profile: "Ambicioso",
    youth_commitment: "Sim",
    family_decision_structure: "Mãe decide",
    guardian_name: "Ana Ferreira",
    guardian_email: "ana.ferreira@email.com",
    guardian_whatsapp: "21976543211",
    guardian_profession: "Analista de Marketing",
    address_cep: "22411-000",
    address_street: "Rua Visconde de Pirajá",
    address_number: "550",
    address_complement: null,
    address_neighborhood: "Ipanema",
    address_city: "Rio de Janeiro",
    address_state: "RJ",
    status: "new",
    notes: null,
    qualified: true,
    qualification_classification: "MORNO",
    qualification_reason: "Moradora em Ipanema sugere alto padrão de vida. Analista de Marketing pode ter renda variável.",
    qualification_confidence: "MEDIA",
    qualified_at: daysAgo(1),
    whatsapp_sent_at: null,
    followup_1_sent_at: null,
    followup_2_sent_at: null,
    meeting_scheduled: null,
    meeting_scheduled_at: null,
    address_country: "BR",
    utm_source: null, utm_medium: null, utm_campaign: null, utm_content: null, utm_term: null, referrer_url: null, landing_url: null, session_id: null, cta_source: null, device_type: null, form_started_at: null,
    is_in_pipeline: false,
    pipeline_stage: null,
    pipeline_deal_id: null,
    pipeline_atleta_id: null,
  },
  {
    id: "3",
    submission_id: "sub_003",
    submitted_at: daysAgo(2),
    updated_at: daysAgo(2),
    athlete_name: "Pedro Alves Costa",
    email: "pedro.costa@gmail.com",
    birth_date: "2009-05-10",
    age: "16",
    athlete_whatsapp: "31965432109",
    position: "Goleiro",
    club_history: "América-MG Sub-16",
    achievements: "Melhor goleiro do Campeonato Mineiro Sub-16",
    video_highlights: null,
    instagram: "@pedro_goleiro1",
    school_year: "1º ano EM",
    current_school: "Colégio Pitágoras",
    school_city_state: "Belo Horizonte - MG",
    education_model: "Particular",
    english_level: "Avançado",
    academic_performance: "Excelente (9-10)",
    start_timing: "2027",
    project_direction: "Universidade via bolsa esportiva",
    investment_range: "30k-40k",
    behavioral_profile: "Disciplinado e focado",
    youth_commitment: "Sim, muito comprometido",
    family_decision_structure: "Pai decide",
    guardian_name: "Carlos Costa",
    guardian_email: "carlos.costa@empresa.com.br",
    guardian_whatsapp: "31965432108",
    guardian_profession: "Engenheiro Civil",
    address_cep: "30112-010",
    address_street: "Av. Afonso Pena",
    address_number: "1000",
    address_complement: "Sala 1001",
    address_neighborhood: "Centro",
    address_city: "Belo Horizonte",
    address_state: "MG",
    status: "new",
    notes: "Atleta com perfil muito forte. Pai interessado em conhecer mais sobre o processo.",
    qualified: true,
    qualification_classification: "QUENTE",
    qualification_reason: "Engenheiro Civil com renda compatível. Atleta com inglês avançado e excelente desempenho acadêmico.",
    qualification_confidence: "ALTA",
    qualified_at: daysAgo(2),
    whatsapp_sent_at: daysAgo(1),
    followup_1_sent_at: null,
    followup_2_sent_at: null,
    meeting_scheduled: null,
    meeting_scheduled_at: null,
    address_country: "BR",
    utm_source: null, utm_medium: null, utm_campaign: null, utm_content: null, utm_term: null, referrer_url: null, landing_url: null, session_id: null, cta_source: null, device_type: null, form_started_at: null,
    is_in_pipeline: true,
    pipeline_stage: "diagnostico_fit",
    pipeline_deal_id: "deal_003",
    pipeline_atleta_id: "atleta_003",
  },
  {
    id: "4",
    submission_id: "sub_004",
    submitted_at: daysAgo(3),
    updated_at: daysAgo(3),
    athlete_name: "Matheus Rodrigues Silva",
    email: "matheus.silva@email.com",
    birth_date: "2008-08-30",
    age: "17",
    athlete_whatsapp: "11954321098",
    position: "Lateral Direito",
    club_history: "Santos FC Sub-17",
    achievements: "Vice-campeão Copa SP de Futebol Júnior",
    video_highlights: "https://vimeo.com/123456",
    instagram: "@matheusrod2",
    school_year: "2º ano EM",
    current_school: "ETEC Santos",
    school_city_state: "Santos - SP",
    education_model: "Público",
    english_level: "Básico",
    academic_performance: "Bom (7-8)",
    start_timing: "2026",
    project_direction: "High School",
    investment_range: "15k-20k",
    behavioral_profile: "Esforçado",
    youth_commitment: "Sim",
    family_decision_structure: "Ambos os pais",
    guardian_name: "José Rodrigues",
    guardian_email: "jose.rodrigues@email.com",
    guardian_whatsapp: "11954321097",
    guardian_profession: "Técnico em Manutenção",
    address_cep: "11013-000",
    address_street: "Rua do Comércio",
    address_number: "23",
    address_complement: null,
    address_neighborhood: "Centro",
    address_city: "Santos",
    address_state: "SP",
    status: "new",
    notes: null,
    qualified: false,
    qualification_classification: "FRIO",
    qualification_reason: "Profissão incompatível com faixa de investimento de US$ 15-20k. Escola pública em cidade interiorana sem indicadores de alto padrão.",
    qualification_confidence: "ALTA",
    qualified_at: daysAgo(3),
    whatsapp_sent_at: null,
    followup_1_sent_at: null,
    followup_2_sent_at: null,
    meeting_scheduled: null,
    meeting_scheduled_at: null,
    address_country: "BR",
    utm_source: null, utm_medium: null, utm_campaign: null, utm_content: null, utm_term: null, referrer_url: null, landing_url: null, session_id: null, cta_source: null, device_type: null, form_started_at: null,
    is_in_pipeline: false,
    pipeline_stage: null,
    pipeline_deal_id: null,
    pipeline_atleta_id: null,
  },
  {
    id: "5",
    submission_id: "sub_005",
    submitted_at: daysAgo(4),
    updated_at: daysAgo(4),
    athlete_name: "Rafael Oliveira Mendes",
    email: "rafael.mendes@email.com",
    birth_date: "2007-01-15",
    age: "18",
    athlete_whatsapp: "47943210987",
    position: "Zagueiro",
    club_history: "Joinville EC Sub-18, Figueirense Sub-16",
    achievements: "Campeão Catarinense Sub-17",
    video_highlights: "https://youtube.com/watch?v=ghi789",
    instagram: "@rafamendes5",
    school_year: "3º ano EM",
    current_school: "Colégio Bom Jesus",
    school_city_state: "Joinville - SC",
    education_model: "Particular",
    english_level: "Intermediário",
    academic_performance: "Bom (7-8)",
    start_timing: "2025",
    project_direction: "Universidade nos EUA",
    investment_range: "50k-70k",
    behavioral_profile: "Liderança natural",
    youth_commitment: "Sim, capitão do time",
    family_decision_structure: "Pai decide",
    guardian_name: "Fernando Mendes",
    guardian_email: "fernando.mendes@empresa.com",
    guardian_whatsapp: "47943210986",
    guardian_profession: "Empresário",
    address_cep: "89201-400",
    address_street: "Rua São Paulo",
    address_number: "350",
    address_complement: "Casa",
    address_neighborhood: "América",
    address_city: "Joinville",
    address_state: "SC",
    status: "new",
    notes: "Empresário com empresa própria. Alto potencial de conversão.",
    qualified: true,
    qualification_classification: "QUENTE",
    qualification_reason: "Empresário — renda variável, mas perfil compatível com faixa de US$ 50-70k. Atleta capitão com trajetória sólida.",
    qualification_confidence: "ALTA",
    qualified_at: daysAgo(4),
    whatsapp_sent_at: daysAgo(3),
    followup_1_sent_at: daysAgo(1),
    followup_2_sent_at: null,
    meeting_scheduled: true,
    meeting_scheduled_at: daysAgo(0),
    address_country: "BR",
    utm_source: null, utm_medium: null, utm_campaign: null, utm_content: null, utm_term: null, referrer_url: null, landing_url: null, session_id: null, cta_source: null, device_type: null, form_started_at: null,
    is_in_pipeline: false,
    pipeline_stage: null,
    pipeline_deal_id: null,
    pipeline_atleta_id: null,
  },
  {
    id: "6",
    submission_id: "sub_006",
    submitted_at: daysAgo(5),
    updated_at: daysAgo(5),
    athlete_name: "Thiago Santos Pereira",
    email: "thiago.pereira@gmail.com",
    birth_date: "2009-09-20",
    age: "15",
    athlete_whatsapp: "85932109876",
    position: "Meia-atacante",
    club_history: "Fortaleza EC Sub-15",
    achievements: "Artilheiro regional Sub-15",
    video_highlights: null,
    instagram: "@thiagosp10",
    school_year: "1º ano EM",
    current_school: "Colégio Ari de Sá",
    school_city_state: "Fortaleza - CE",
    education_model: "Particular",
    english_level: "Básico",
    academic_performance: "Regular (5-6)",
    start_timing: "2027",
    project_direction: "High School + Universidade",
    investment_range: "20k-30k",
    behavioral_profile: "Criativo",
    youth_commitment: "Sim",
    family_decision_structure: "Mãe decide",
    guardian_name: "Carla Santos",
    guardian_email: "carla.santos@email.com",
    guardian_whatsapp: "85932109875",
    guardian_profession: "Professora",
    address_cep: "60110-000",
    address_street: "Av. Beira Mar",
    address_number: "1200",
    address_complement: "Apto 801",
    address_neighborhood: "Meireles",
    address_city: "Fortaleza",
    address_state: "CE",
    status: "new",
    notes: null,
    qualified: true,
    qualification_classification: "MORNO",
    qualification_reason: "Professora — renda potencialmente insuficiente, mas apartamento em Meireles (bairro nobre) indica padrão de vida elevado.",
    qualification_confidence: "MEDIA",
    qualified_at: daysAgo(5),
    whatsapp_sent_at: daysAgo(4),
    followup_1_sent_at: daysAgo(2),
    followup_2_sent_at: null,
    meeting_scheduled: null,
    meeting_scheduled_at: null,
    address_country: "BR",
    utm_source: null, utm_medium: null, utm_campaign: null, utm_content: null, utm_term: null, referrer_url: null, landing_url: null, session_id: null, cta_source: null, device_type: null, form_started_at: null,
    is_in_pipeline: false,
    pipeline_stage: null,
    pipeline_deal_id: null,
    pipeline_atleta_id: null,
  },
  {
    id: "7",
    submission_id: "sub_007",
    submitted_at: daysAgo(7),
    updated_at: daysAgo(7),
    athlete_name: "Bruno Carvalho Neto",
    email: "bruno.neto@email.com",
    birth_date: "2008-06-05",
    age: "17",
    athlete_whatsapp: "61921098765",
    position: "Volante",
    club_history: "Brasiliense FC Sub-17",
    achievements: "Campeão Candango Sub-17",
    video_highlights: "https://youtube.com/watch?v=jkl012",
    instagram: "@brunoneto8",
    school_year: "2º ano EM",
    current_school: "Colégio Militar de Brasília",
    school_city_state: "Brasília - DF",
    education_model: "Público",
    english_level: "Intermediário",
    academic_performance: "Excelente (9-10)",
    start_timing: "2026",
    project_direction: "Universidade nos EUA",
    investment_range: "30k-40k",
    behavioral_profile: "Disciplinado e metódico",
    youth_commitment: "Sim, muito dedicado",
    family_decision_structure: "Pai decide",
    guardian_name: "General Paulo Carvalho",
    guardian_email: "paulo.carvalho@eb.mil.br",
    guardian_whatsapp: "61921098764",
    guardian_profession: "Militar (General)",
    address_cep: "70040-010",
    address_street: "SHIS QL 12",
    address_number: "5",
    address_complement: "Casa",
    address_neighborhood: "Lago Sul",
    address_city: "Brasília",
    address_state: "DF",
    status: "new",
    notes: "General do Exército — renda e estabilidade compatíveis. Atleta do CMB com excelente desempenho.",
    qualified: true,
    qualification_classification: "QUENTE",
    qualification_reason: "General do Exército — renda e benefícios compatíveis. Lago Sul é bairro de alto padrão.",
    qualification_confidence: "ALTA",
    qualified_at: daysAgo(7),
    whatsapp_sent_at: daysAgo(5),
    followup_1_sent_at: daysAgo(3),
    followup_2_sent_at: daysAgo(0),
    meeting_scheduled: null,
    meeting_scheduled_at: null,
    address_country: "BR",
    utm_source: null, utm_medium: null, utm_campaign: null, utm_content: null, utm_term: null, referrer_url: null, landing_url: null, session_id: null, cta_source: null, device_type: null, form_started_at: null,
    is_in_pipeline: false,
    pipeline_stage: null,
    pipeline_deal_id: null,
    pipeline_atleta_id: null,
  },
  {
    id: "8",
    submission_id: "sub_008",
    submitted_at: daysAgo(10),
    updated_at: daysAgo(10),
    athlete_name: "Victor Henrique Barbosa",
    email: "victor.barbosa@gmail.com",
    birth_date: "2007-12-01",
    age: "18",
    athlete_whatsapp: "51910987654",
    position: "Ponta Esquerda",
    club_history: "Grêmio Sub-18, Internacional Sub-16",
    achievements: "Vice-campeão Copa do Brasil Sub-17",
    video_highlights: "https://youtube.com/watch?v=mno345",
    instagram: "@victorhb11",
    school_year: "3º ano EM",
    current_school: "Colégio Santa Inês",
    school_city_state: "Porto Alegre - RS",
    education_model: "Particular",
    english_level: "Avançado",
    academic_performance: "Excelente (9-10)",
    start_timing: "2025",
    project_direction: "High School + Universidade",
    investment_range: "over-70k",
    behavioral_profile: "Profissional nato",
    youth_commitment: "Sim, nível de profissional",
    family_decision_structure: "Ambos os pais",
    guardian_name: "Alexandre Barbosa",
    guardian_email: "alexandre.barbosa@grupo.com.br",
    guardian_whatsapp: "51910987653",
    guardian_profession: "CEO",
    address_cep: "90830-000",
    address_street: "Av. Nilo Peçanha",
    address_number: "2900",
    address_complement: "Cobertura",
    address_neighborhood: "Boa Vista",
    address_city: "Porto Alegre",
    address_state: "RS",
    status: "new",
    notes: "CEO de grande empresa. Atleta com trajetória excelente. Alta probabilidade de conversão.",
    qualified: true,
    qualification_classification: "QUENTE",
    qualification_reason: "CEO com renda amplamente compatível com faixa acima de US$ 70k. Atleta formado em Grêmio e Inter.",
    qualification_confidence: "ALTA",
    qualified_at: daysAgo(10),
    whatsapp_sent_at: daysAgo(8),
    followup_1_sent_at: daysAgo(6),
    followup_2_sent_at: daysAgo(1),
    meeting_scheduled: null,
    meeting_scheduled_at: null,
    address_country: "US",
    utm_source: null, utm_medium: null, utm_campaign: null, utm_content: null, utm_term: null, referrer_url: null, landing_url: null, session_id: null, cta_source: null, device_type: null, form_started_at: null,
    is_in_pipeline: false,
    pipeline_stage: null,
    pipeline_deal_id: null,
    pipeline_atleta_id: null,
  },
];

export const MOCK_METRICS: LeadMetrics = {
  total: MOCK_LEADS.length,
  quente: MOCK_LEADS.filter((l) => l.qualification_classification === "QUENTE").length,
  morno: MOCK_LEADS.filter((l) => l.qualification_classification === "MORNO").length,
  frio: MOCK_LEADS.filter((l) => l.qualification_classification === "FRIO").length,
  pendingWhatsApp: MOCK_LEADS.filter(
    (l) =>
      l.whatsapp_sent_at === null &&
      (l.qualification_classification === "QUENTE" || l.qualification_classification === "MORNO")
  ).length,
  whatsappSent: MOCK_LEADS.filter((l) => l.whatsapp_sent_at !== null).length,
  todayCount: MOCK_LEADS.filter((l) => {
    const d = new Date(l.submitted_at);
    const today = new Date();
    return d.toDateString() === today.toDateString();
  }).length,
  weekCount: MOCK_LEADS.filter((l) => {
    const d = new Date(l.submitted_at);
    const weekAgo = new Date();
    weekAgo.setDate(weekAgo.getDate() - 7);
    return d > weekAgo;
  }).length,
};

function generateDailyData(): DailyLeadCount[] {
  const days: DailyLeadCount[] = [];
  for (let i = 29; i >= 0; i--) {
    const date = new Date();
    date.setDate(date.getDate() - i);
    const dateStr = date.toISOString().split("T")[0];

    const dayLeads = MOCK_LEADS.filter(
      (l) => l.submitted_at.split("T")[0] === dateStr
    );

    days.push({
      date: dateStr,
      total: dayLeads.length || (i < 15 ? Math.floor(Math.random() * 3) : 0),
      quente: dayLeads.filter((l) => l.qualification_classification === "QUENTE").length,
      morno: dayLeads.filter((l) => l.qualification_classification === "MORNO").length,
      frio: dayLeads.filter((l) => l.qualification_classification === "FRIO").length,
    });
  }
  return days;
}

export const MOCK_DAILY_DATA: DailyLeadCount[] = generateDailyData();
